image: keymetrics/pm2:6

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "make deploy"
    - pm2 deploy ecosystem.config.js production
    - pm2 restart main
  environment:
    name: deploying
  only:
  - dev
